kind: Deployment
apiVersion: apps/v1
metadata:
  name: publish
  labels: 
    app: publish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publish
  template:
    metadata:
      labels:
        app: publish
    spec:
      containers:
        - name: publish
          image: flerpo/kafka:publish
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 20m
              memory: 80Mi
